### ISSUE TITLE
ASN1 corrupted data exception on linux

### ISSUE THREAD

**Issue by Mrizzi-96** [DevTrevi/DgcReader#59]
Environment: Linux OL7 with dotnet-runtime-5.0
Latest nuget packages (2.2.1) or d21ca6d84643f47426be77ed5756022ff33a5785 when calling ItalianTrustListProvider.RefreshTrustlist() throws exception
```
DgcReader.TrustListProviders.Italy.ItalianTrustListProvider[0]
   Error getting trustlist from server: ASN1 corrupted data.
   System.Security.Cryptography.CryptographicException: ASN1 corrupted data.
    ---> System.Formats.Asn1.AsnContentException: The provided data is tagged with 'Application' class value '13', but it should have 
 been 'Universal' class value '16'.
   at System.Formats.Asn1.AsnDecoder.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber
   at System.Formats.Asn1.AsnDecoder.ReadSequence(ReadOnlySpan source, AsnEncodingRules ruleSet, Int32& contentOffset, Int32& 
       contentLength, Int32& bytesConsumed, Nullable expectedTag)
   at System.Formats.Asn1.AsnValueReader.ReadSequence(Nullable expectedTag)
   at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.DecodeCore(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory rebind, PfxAsn& decoded)
    at System.Security.Cryptography.Asn1.Pkcs12.PfxAsn.Decode(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory rebind, PfxAsn& decoded)
        --- End of inner exception stack trace ---
```

I already solved this issue in another library. It's related to Italian data and how dotnet handles cryptography on Linux and MacOS runtimes. Basically, platforms <> Windows do not automatically convert the Byte array `rawData` to base 64, hence the X509Certificate constructor cannot read it. [Reference](https://github.com/dotnet/runtime/issues/47005).

I'm going to submit a pull request in a while.

Marco.

**Comment by DevTrevi** [comment]
Fixed in v2.3.0, thank you @Mrizzi-96!

**Comment by Mrizzi-96** [comment]
Found another occurrence of the bug at:
```
[CUT]
at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData)
at DgcReader.RuleValidators.Italy.CertificateExtendedKeyUsageUtils.GetExtendedKeyUsages(SignatureValidationResult signatureValidation, ILogger logger) 
```
The fix will be ready soon as a pull request.

**Comment by DevTrevi** [comment]
Hi @Mrizzi-96 , I replyed into the PR, I found that the real bug is in another place of the library :)
